{{- $config := index .Values.apps "sale-form-backend" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sale-form-backend
  labels:
    app: sale-form-backend
spec:
  replicas: {{ $config.image.replicas }}
  selector:
    matchLabels:
      app: sale-form-form-backend
  template:
    metadata:
      labels:
        app: sale-form-form-backend
    spec:
      containers:
      - name: sale-form-backend-container
        image: "{{ $config.image.repository }}:{{ $config.image.tag }}"
        ports:
        {{- range $portConfig := $config.service.ports }}
          - name: {{ $portConfig.name }}
            containerPort: {{ $portConfig.port }}
        {{- end }}
        resources:
{{ toYaml $config.resources | nindent 10 }}