{{- $config := .Values.apps.apitestapp -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apitestapp
  labels:
    app: apitestapp
spec:
  # Jeśli w values nie ma replicas, domyślnie ustawiamy 1
  replicas: {{ $config.image.replicas | default 1 }}
  selector:
    matchLabels:
      app: apitestapp
  template:
    metadata:
      labels:
        app: apitestapp
    spec:
      containers:
      - name: api-container
        image: "{{ $config.image.repository }}:{{ $config.image.tag }}"
        ports:
        {{- range $portConfig := $config.service.ports }}
        - name: {{ $portConfig.name }}
          containerPort: {{ $portConfig.port }}
        {{- end }}
        
        # API zazwyczaj potrzebuje zasobów, pobieramy je z values
        resources:
          {{- toYaml $config.resources | nindent 10 }}
        
        # Tutaj możesz w przyszłości dopisać env, np.:
        # env:
        #   - name: DATABASE_URL
        #     value: "postgres://user:password@db-service:5432/mydb"