{{- range $appName, $appConfig := .Values.apps }}
{{- if and $appConfig.ingress $appConfig.ingress.enabled }}
{{- $kebabName := $appName | regexReplaceAll "([A-Z])" "-$1" | lower | trimPrefix "-" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $kebabName }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: {{ $appConfig.ingress.uploadLimit | default "1m" | quote }}
spec:
  rules:
  - host: {{ $appConfig.ingress.host | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $kebabName }}-service
            port:
              number: {{ $appConfig.ingress.ingressPort }}
---
{{- end }}
{{- end }}