{{- range $appName, $appConfig := .Values.apps }}
{{- $kebabName := $appName | regexReplaceAll "([A-Z])" "-$1" | lower | trimPrefix "-" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $kebabName }}-service
spec:
  selector:
    app: {{ $kebabName }}
  type: {{ $appConfig.service.type | default "ClusterIP" }}
  ports:
  {{- range $portConfig := $appConfig.service.ports }}
  - name: {{ $portConfig.name }}
    protocol: TCP
    port: {{ $portConfig.port }}
    targetPort: {{ $portConfig.name }}
  {{- end }}
---
{{- end }}