apps:
  frontend:
    image:
      repository: radeczu/angular-sandbox
      tag: arm64
      replicas: 1
    service:
          type: LoadBalancer
          ports:
            - name: status
              port: 8080
            - name: dev
              port: 4200
    persistence:
      enabled: true
      claimName: frontend-pvc
      size: "2Gi"
    ingress:
      enabled: true
      host: dev.crm.pi
      ingressPort: 4200
      uploadLimit: "50m"
    resources:
      requests: { cpu: "100m", memory: "256Mi" }
      limits: { cpu: "500m", memory: "512Mi" }
  formBackend:
    image:
      repository: radeczu/multi-form-backend
      tag: arm64
      replicas: 1
    service:
      type: ClusterIP
      ports:
        - name: api
          port: 3000
    persistence:
      enabled: false
    ingress:
      enabled: false
    resources:
      requests: { cpu: "50m", memory: "128Mi" }
      limits: { cpu: "200m", memory: "256Mi" }

  # apitestapp:
  #   image:
  #     repository: radeczu/apitestapp
  #     tag: latest
  #   service:
  #     type: ClusterIP
  #     ports:
  #       - name: api
  #         port: 2137
  #   ingress:
  #     enabled: false